on:
  pull_request:
    paths:
      - "cmd/**"
      - "pkg/**"
      - "postrender/**"
  push:
    branches:
      - main


name: Lint 
jobs:
  tidy:
    name: Module checks
    runs-on: ubuntu-22.04
    steps:
      - name: Check out sources
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          filter: tree:0
      - name: Set up environment
        uses: ./.github/actions/setup
      - name: Run make tidy
        run: make tidy
      - name: Run make vet
        run: make vet
      - name: Check changed files
        id: check-changed-files
        uses: tj-actions/verify-changed-files@v20
        with:
          read-gitignore: true
      - name: List changed files
        if: steps.check-changed-files.outputs.files_changed == 'true'
        env:
          CHANGED_FILES: ${{ steps.check-changed-files.outputs.changed_files }}
        run: |
          cat <<- EOF
            Unexpected file changes:
            $CHANGED_FILES

            Please run \`make tidy\` and try again.
          EOF
          exit 1
  golangci:
    name: Linting
    runs-on: ubuntu-22.04
    steps:
      - name: Check out sources
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          filter: tree:0
      - name: Set up environment
        uses: ./.github/actions/setup
      - name: Formatting
        run: make fmt
      - name: Run golangci-lint
        uses: golangci/golangci-lint-action@v8
        with:
          args: --timeout=5m
          version: latest