name: Release with GoReleaser

on:

  push:
    tags:
      - 'v*'
      
permissions:
  contents: write

jobs:
  release:
    runs-on: ubuntu-latest
    if: >
      (github.event_name == 'workflow_run' && github.event.workflow_run.conclusion == 'success')
      || github.event_name == 'push'

    steps:
      - name: Check out sources
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          filter: tree:0

      - name: Set up environment
        uses: ./.github/actions/setup

      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v2
        with:
          args: release --clean
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
