on:
  pull_request:
    paths:
      - "cmd/**"
      - "pkg/**"
      - "postrender/**"
  push:
    branches:
      - main

name: Test 
jobs:
  unittests:
    name: Unit tests
    runs-on: ubuntu-22.04
    steps:
      - name: Check out sources
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          filter: tree:0
      - name: Set up environment
        uses: ./.github/actions/setup
      - name: Run make test
        run: make test